name: Bug Report
description: File a bug report.
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? You must attach a screenshot and any logs that you have. Please ensure your browser console is open when taking the screenshot.
    validations:
      required: true
  - type: dropdown
    id: apps
    attributes:
      label: What applications(s) are you using?
      multiple: true
      options:
        - Hub (XP)
        - Hub (Send & Receive)
        - Hub (Other)
        - Explorer
        - Docs
        - RPC Service
        - Third Party Application
        - Other
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Where are you seeing the issue?
      multiple: true
      options:
        - Mainnet
        - Testnet (athens3)
        - Localnet
    validations:
      required: true
  - type: dropdown
    id: persona
    attributes:
      label: Who are you?
      multiple: true
      options:
        - Individual
        - Business
        - Application Developer
        - Infrastructure Provider
        - Researcher
        - Other
    validations:
      required: true
  - type: dropdown
    id: wallets
    attributes:
      label: What wallet(s) are you using?
      multiple: true
      options:
        - Metamask
        - UniSat
        - OKX Wallet
        - Coinbase Wallet
        - XDEFI Wallet
        - Phantom
        - Other
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Chromium
        - Brave
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true