name: Having difficulties setting up or syncing a node
description: Please fill out the following form to help us understand and resolve your issue with setting up or syncing a node. Provide as much detail as possible to ensure a quick and accurate resolution.
labels: ["infra", "triage"]
body:
  - type: dropdown
    attributes:
      label: Which environment are you setting a node for?
      options:
        - Mainnet
        - Testnet
  - type: dropdown
    attributes:
      label: Does your machine match the technical requirements?
      description: See https://www.zetachain.com/docs/nodes/start-here/requirements/
      options:
        - "Yes"
        - "No"
  - type: dropdown
    attributes:
      label: Have you completed the setup?
      description: See https://www.zetachain.com/docs/nodes/start-here/setup/
      options:
        - "Yes"
        - "No"
  - type: dropdown
    attributes:
      label: Which method are you using?
      description: If you used different methods, please, create separate issues.
      options:
        - Snapshot
        - KSYNC
  - type: dropdown
    attributes:
      label: Did you build your binary from source or download it from the Releases page?
      description: "We recommend using binaries from our Releases page: https://github.com/zeta-chain/node/releases"
      options:
        - "Downloaded from Releases page"
        - "Built locally"
  - type: textarea
    attributes:
      label: Please, share the contents of config.toml
      description: By default the file is in `$HOME/.zetacored/config/`
  - type: textarea
    attributes:
      label: Please, share the contents of app.toml
      description: By default the file is in `$HOME/.zetacored/config/`
  - type: textarea
    attributes:
      label: Additional details
      description: Any other information that might help us resolve your issue.
